[2024-01-31T15:34:59.700+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cvd_automation_pipeline.run_nuclei_scan_task manual__2024-01-31T15:34:47.692492+00:00 [queued]>
[2024-01-31T15:34:59.708+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cvd_automation_pipeline.run_nuclei_scan_task manual__2024-01-31T15:34:47.692492+00:00 [queued]>
[2024-01-31T15:34:59.708+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-01-31T15:34:59.723+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_nuclei_scan_task> on 2024-01-31 15:34:47.692492+00:00
[2024-01-31T15:34:59.727+0000] {standard_task_runner.py:60} INFO - Started process 16629 to run task
[2024-01-31T15:34:59.729+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cvd_automation_pipeline', 'run_nuclei_scan_task', 'manual__2024-01-31T15:34:47.692492+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/cvd_pipeline_1.py', '--cfg-path', '/tmp/tmpzb07k5tb']
[2024-01-31T15:34:59.730+0000] {standard_task_runner.py:88} INFO - Job 45: Subtask run_nuclei_scan_task
[2024-01-31T15:34:59.763+0000] {task_command.py:423} INFO - Running <TaskInstance: cvd_automation_pipeline.run_nuclei_scan_task manual__2024-01-31T15:34:47.692492+00:00 [running]> on host 8d8bbdf320cd
[2024-01-31T15:34:59.828+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cvd_automation_pipeline' AIRFLOW_CTX_TASK_ID='run_nuclei_scan_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-31T15:34:47.692492+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-31T15:34:47.692492+00:00'
[2024-01-31T15:35:05.784+0000] {logging_mixin.py:188} INFO - An error occurred while reading the file: [Errno 2] No such file or directory: 'data/nuclei_json_results/formatted_output_0.json'
[2024-01-31T15:35:05.785+0000] {logging_mixin.py:188} INFO - Nuclei scan completed.
[2024-01-31T15:35:05.786+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-31T15:35:05.794+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=cvd_automation_pipeline, task_id=run_nuclei_scan_task, execution_date=20240131T153447, start_date=20240131T153459, end_date=20240131T153505
[2024-01-31T15:35:05.808+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-31T15:35:05.824+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
